// <auto-generated />
namespace AspNetMvcPdfISharp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initseed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initseed));
        
        string IMigrationMetadata.Id
        {
            get { return "202311270837127_initseed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
